const translations = {
    uz: {
        nav_services: "Xizmatlar",
        nav_portfolio: "Portfolio",
        nav_pricing: "Narxlar",
        nav_faq: "FAQ",
        nav_order_btn: "Buyurtma berish",
        hero_badge: "Landing Pages & Business Automation",
        hero_title_1: "Biznesingiz uchun",
        hero_title_2: "raqamli sotuv tizimlari",
        hero_desc: "Biz mijoz jalb qiluvchi tezyurar Landing Pagelar yaratamiz, Instagram API va Telegram botlar orqali arizalarni avtomatlashtirib Google Jadvallarga ulaymiz va professional Target reklamalarini yoqib beramiz.",
        hero_btn_start: "Loyihani boshlash",
        hero_btn_portfolio: "Bajarilgan ishlar",
        stack_title: "Biz ishlatadigan professional asboblar",
        services_title: "Sizga qanday yechimlar kerak?",
        services_desc: "Biznesingizni yangi bosqichga olib chiquvchi yo'nalishlarimiz.",
        service_1_title: "Premium Landing Pages",
        service_1_desc: "Mijozlarni birinchi soniyadanoq jalb qiluvchi, ultra tez yuklanadigan, zamonaviy va mukammal bir sahifali veb-saytlar.",
        service_2_title: "Xabarlar va Bot Avtomatizatsiyasi",
        service_2_desc: "Instagram API orqali avtomat javoblar yuborish, saytni Telegram botga ulash, arizalarni real vaqtda Google Jadvallar va guruhlarga yuborish.",
        service_3_title: "Target Reklama (Meta Ads)",
        service_3_desc: "Yaratilgan saytingizga tayyor mijozlar oqimini olib kelish uchun Facebook va Instagram ijtimoiy tarmoqlarida professional target yoqib berish.",
        portfolio_title: "Real Loyihalarimiz",
        portfolio_desc: "Bizning mahoratimizni isbotlovchi amaldagi real keyslar.",
        p1_title: "Fast-Food Buyurtma Sahifasi",
        p1_desc: "Mijozlar taomlarni tanlab, buyurtma tugmasini bosganda, barcha ma'lumotlar avtomat ravishda kafe xodimlari Telegram guruhiga va Google Jadvallarga yetib boradigan tizim.",
        p2_title: "Klinika uchun Premium Landing",
        p2_desc: "Tibbiyot markazi uchun yaratilgan konversiyasi yuqori veb-sahifa. Unga professional target reklamasi sozlab berilgan, arizalar to'g'ridan-to'g'ri Google Sheet jadvallarida jamlanadi.",
        p3_title: "Onlayn Kitob Do'koni Vitrinasi",
        p3_desc: "Kitob mahsulotlarini chiroyli va qulay filtrlash imkoniyatiga ega katalog sayt. Har bir xarid arizasi Google Jadvallar bazasiga integratsiya qilingan.",
        p4_title: "An'anaviy Tapchan Galereya Sayti",
        p4_desc: "Milliy va zamonaviy tapchan dizaynlarining professional chizmalari hamda rasmlarini taqdim etuvchi, tez ishlaydigan interaktiv vitrina-sahifa.",
        pricing_title: "Shaffof Tariflar va Paketlar",
        pricing_desc: "Sizga kerakli xizmatlar ko'lamini tanlang.",
        plan_1_subtitle: "Kichik biznes yoki shaxsiy brend uchun vizitka sayt",
        p1_f1: "1-3 sahifali Landing Page (HTML/CSS)",
        p1_f2: "To'liq mobil moslashuvchanlik",
        p1_f3: "Bepul Domen ulab berish",
        p1_f4: "Tezkor yuklanish optimizatsiyasi",
        select_plan: "Tanlash",
        popular: "Mashhur",
        plan_2_subtitle: "Mijoz yig'uvchi sayt + mukammal tizimlar ulanishi",
        p2_f1: "Premium UI/UX Landing Page",
        p2_f2: "Google Sheets (Jadval) integratsiyasi",
        p2_f3: "Telegram Bot & Guruhga bildirishnomalar",
        p2_f4: "Instagram API avtomatlashtirish ulanishi",
        plan_3_subtitle: "Tayyor veb-sayt tizimi va mijozlar oqimi birga",
        p3_f1: "To'liq VIP Avtomatizatsiya paketi",
        p3_f2: "Facebook & Instagram Target sozlash",
        p3_f3: "Kreativ reklama matnlari va takliflar",
        p3_f4: "7 kunlik reklama monitoringi",
        faq_title: "Ko'p beriladigan savollar",
        faq_desc: "Asosiy savollarga ochiq va aniq javoblarimiz.",
        faq_q1: "Saytga kelgan arizalarni qayerda ko'ramiz?",
        faq_a1: "Barcha arizalar real vaqt rejimida sizning Google Drive hisobingizdagi Google Sheets (Jadval) fayliga tushadi. Shuningdek, qulaylik uchun ularni Telegram guruhingizga bot orqali bir soniyada yo'naltirib beramiz.",
        faq_q2: "Instagram avtomatlashtirish nima beradi?",
        faq_a2: "Mijoz Instagram Direct yoki izohlarda ma'lum bir so'zni yozganda (masalan: 'narxi'), biz o'rnatgan API tizimi unga avtomatik ravishda sayt havolasini yoki maxsus taklifni yuboradi va mijozni sadoqatli xaridorga aylantiradi.",
        faq_q3: "Target reklama uchun budjetni kim beradi?",
        faq_a3: "Bizning xizmat narximiz faqatgina reklamani to'g'ri va professional sozlashni o'z ichiga oladi. Reklamaning kunlik yoki oylik budjeti (Meta kompaniyasiga to'lanadigan pul) mijoz tomonidan alohida taqdim etiladi.",
        form_title: "Keling, loyihangizni boshlaymiz",
        form_desc: "Formani to'ldiring. Biz biznesingiz uchun eng mukammal raqamli yechimni taklif qilamiz.",
        form_label_name: "Ismingiz",
        form_placeholder_name: "Alisher",
        form_label_surname: "Familiyangiz",
        form_placeholder_surname: "Asimov",
        form_label_phone: "Telefon raqamingiz",
        form_placeholder_number: "+998",
        form_label_package: "Sizga qaysi paket mos keladi?",
        form_label_desc: "Loyiha haqida qisqacha tavsif (Ixtiyoriy)",
        form_submit: "Arizani yuborish",
        footer_text: "Biznesingizni avtomatlashtirish bo'yicha sizning professional raqamli hamkoringiz.",
        contacts_text: "Kontaktlar",
        adress_text: "Toshkent sh., Chilonzor tumani, 5-mavze",
        ish_text: "Ish vaqti.",
        kun_text: "Dush - Juma:",
        shanba_text: "Shanba:",
        dam_text: "Yakshanba: Dam olish",
        social_text: "Bizni kuzating",
        copy_text: "&copy; 2026 DEV.ALOSHIY.COM — Barcha huquqlar himoyalangan."
    },
    ru: {
        nav_services: "Услуги",
        nav_portfolio: "Портфолио",
        nav_pricing: "Цены",
        nav_faq: "FAQ",
        nav_order_btn: "Заказать",
        hero_badge: "Landing Pages & Business Automation",
        hero_title_1: "Цифровые системы продаж",
        hero_title_2: "для вашего бизнеса",
        hero_desc: "Мы создаем высококонверсионные Landing Page, автоматизируем заявки через Instagram API и Telegram-боты с интеграцией в Google Таблицы, а также запускаем профессиональный таргетинг.",
        hero_btn_start: "Начать проект",
        hero_btn_portfolio: "Наши работы",
        stack_title: "Профессиональные инструменты, которые мы используем",
        services_title: "Какие решения вам нужны?",
        services_desc: "Направления, которые выведут ваш бизнес на новый уровень.",
        service_1_title: "Premium Landing Pages",
        service_1_desc: "Ультрабыстрые, современные и идеальные одностраничные сайты, привлекающие клиентов с первой секунды.",
        service_2_title: "Автоматизация сообщений и ботов",
        service_2_desc: "Автоматические ответы через Instagram API, подключение сайта к Telegram-боту, отправка заявок в Google Таблицы и группы в реальном времени.",
        service_3_title: "Таргетированная реклама (Meta Ads)",
        service_3_desc: "Профессиональная настройка таргета в Facebook и Instagram для привлечения потока готовых клиентов на ваш сайт.",
        portfolio_title: "Наши реальные проекты",
        portfolio_desc: "Действующие реальные кейсы, доказывающие наше мастерство.",
        p1_title: "Страница заказа Fast-Food",
        p1_desc: "Система, где клиенты выбирают блюда и нажимают кнопку заказа, а все данные автоматически отправляются в Telegram-группу сотрудников кафе и в Google Таблицы.",
        p2_title: "Премиум Landing для клиники",
        p2_desc: "Веб-страница с высокой конверсией, созданная для медицинского центра. Настроена профессиональная реклама, заявки собираются напрямую в Google Sheets.",
        p3_title: "Витрина онлайн-магазина книг",
        p3_desc: "Сайт-каталог с красивой и удобной фильтрацией книжной продукции. Каждая заявка интегрирована с базой данных Google Таблиц.",
        p4_title: "Сайт-галерея традиционных топчанов",
        p4_desc: "Быстрая интерактивная витрина, представляющая профессиональные чертежи и фотографии национальных и современных дизайнов топчанов.",
        pricing_title: "Прозрачные тарифы и пакеты",
        pricing_desc: "Выберите необходимый объем услуг.",
        plan_1_subtitle: "Сайт-визитка для малого бизнеса или личного бренда",
        p1_f1: "Landing Page на 1-3 экрана (HTML/CSS)",
        p1_f2: "Полная мобильная адаптация",
        p1_f3: "Бесплатное подключение домена",
        p1_f4: "Оптимизация скорости загрузки",
        select_plan: "Выбрать",
        popular: "Популярный",
        plan_2_subtitle: "Сайт для сбора клиентов + подключение систем",
        p2_f1: "Premium UI/UX Landing Page",
        p2_f2: "Интеграция с Google Sheets",
        p2_f3: "Уведомления в Telegram Бот и Группу",
        p2_f4: "Подключение автоматизации Instagram API",
        plan_3_subtitle: "Готовая система сайта + поток клиентов",
        p3_f1: "Полный пакет VIP Автоматизации",
        p3_f2: "Настройка таргета Facebook & Instagram",
        p3_f3: "Креативные рекламные тексты и офферы",
        p3_f4: "7 дней мониторинга рекламы",
        faq_title: "Часто задаваемые вопросы",
        faq_desc: "Открытые и четкие ответы на основные вопросы.",
        faq_q1: "Где мы будем видеть заявки с сайта?",
        faq_a1: "Все заявки в режиме реального времени попадают в файл Google Sheets на вашем Google Drive. Также для удобства мы за секунду перенаправляем их в вашу Telegram-группу через бота.",
        faq_q2: "Что дает автоматизация Instagram?",
        faq_a2: "Когда клиент пишет определенное слово в Direct или комментариях (например: 'цена'), установленная нами система API автоматически отправляет ему ссылку на сайт или спецпредложение, превращая его в лояльного покупателя.",
        faq_q3: "Кто оплачивает бюджет на таргетированную рекламу?",
        faq_a3: "Стоимость наших услуг включает только правильную и профессиональную настройку рекламы. Ежедневный или ежемесячный бюджет (деньги, выплачиваемые компании Meta) предоставляется клиентом отдельно.",
        form_title: "Давайте начнем ваш проект",
        form_desc: "Заполните форму. Мы предложим идеальное цифровое решение для вашего бизнеса.",
        form_label_name: "Ваше имя",
        form_placeholder_name: "Алишер",
        form_label_surname: "Ваша фамилия",
        form_placeholder_surname: "Асимов",
        form_label_phone: "Ваш номер телефона",
        form_placeholder_number: "+998",
        form_label_package: "Какой пакет вам подходит?",
        form_label_desc: "Краткое описание проекта (Необязательно)",
        form_submit: "Отправить заявку",
        footer_text: "Ваш профессиональный цифровой партнер по автоматизации бизнеса.",
        contacts_text: "Контакты",
        adress_text: "г.Ош., ул.Айни, 114.",
        ish_text: "График работы.",
        kun_text: "Пониделник - Пятница:",
        shanba_text: "Суббота:",
        dam_text: "Воскресенье: Выходной.",
        social_text: "Подписывайтесь на нас",
        copy_text: "&copy; 2026 DEV.ALOSHIY.COM — Все права защищены.",
    },
    kg: {
        nav_services: "Кызматтар",
        nav_portfolio: "Портфолио",
        nav_pricing: "Баалар",
        nav_faq: "FAQ",
        nav_order_btn: "Буйрутма берүү",
        hero_badge: "Landing Pages & Business Automation",
        hero_title_1: "Сиздин бизнес үчүн",
        hero_title_2: "санариптик сатуу системалары",
        hero_desc: "Биз кардарларды тартуучу тез Landing Page'дерди түзөбүз, Instagram API жана Telegram боттор аркылуу табыштамаларды автоматташтырып Google Таблицаларга туташтырабыз жана кесипкөй Таргет жарнамаларын жүргүзөбүз.",
        hero_btn_start: "Долбоорду баштоо",
        hero_btn_portfolio: "Аткарылган иштер",
        stack_title: "Биз колдонгон кесипкөй куралдар",
        services_title: "Сизге кандай чечимдер керек?",
        services_desc: "Бизнесиңизди жаңы деңгээлге чыгаруучу багыттарыбыз.",
        service_1_title: "Premium Landing Pages",
        service_1_desc: "Кардарларды биринчи секунддан эле тартуучу, өтө тез жүктөлүүчү, заманбап жана идеалдуу бир барактуу веб-сайттар.",
        service_2_title: "Кабарлар жана Бот Автоматташтыруу",
        service_2_desc: "Instagram API аркылуу автоматтык жоопторду жөнөтүү, сайтты Telegram ботко туташтыруу, табыштамаларды реалдуу убакытта Google Таблицаларга жана топторго жөнөтүү.",
        service_3_title: "Таргет Жарнама (Meta Ads)",
        service_3_desc: "Түзүлгөн сайтыңызга даяр кардарлар агымын алып келүү үчүн Facebook жана Instagram социалдык тармактарында кесипкөй таргетти жөндөө.",
        portfolio_title: "Реалдуу Долбоорлорубуз",
        portfolio_desc: "Биздин чеберчилигибизди далилдеген реалдуу кейстер.",
        p1_title: "Fast-Food Буйрутма Барагы",
        p1_desc: "Кардарлар тамактарды тандап, буйрутма баскычын басканда, бардык маалыматтар автоматтык түрдө кафе кызматкерлеринин Telegram тобуна жана Google Таблицаларга жетүүчү система.",
        p2_title: "Клиника үчүн Премиум Landing",
        p2_desc: "Медициналык борбор үчүн түзүлгөн конверсиясы жогору веб-баракча. Ага кесипкөй таргет жарнамасы жөндөлгөн, табыштамалар түздөн-түз Google Sheets таблицаларына чогултулат.",
        p3_title: "Онлайн Китеп Дүкөнү",
        p3_desc: "Китеп продукцияларын кооз жана ыңгайлуу чыпкалоо мүмкүнчүлүгүнө ээ каталог-сайт. Ар бир сатып алуу табыштамасы Google Таблицалар базасына интеграцияланган.",
        p4_title: "Салттуу Топчан Галерея Сайты",
        p4_desc: "Улуттук жана заманбап топчан дизайндарынын кесипкөй чиймелерин жана сүрөттөрүн көрсөтүүчү, тез иштөөчү интерактивдүү витрина-баракча.",
        pricing_title: "Ачык Тарифтер жана Пакеттер",
        pricing_desc: "Сизге керектүү кызматтардын көлөмүн тандаңыз.",
        plan_1_subtitle: "Кичи бизнес же жеке бренд үчүн визитка-сайт",
        p1_f1: "1-3 барактуу Landing Page (HTML/CSS)",
        p1_f2: "Толук мобилдик адаптация",
        p1_f3: "Доменди акысыз туташтыруу",
        p1_f4: "Тез жүктөлүү оптимизациясы",
        select_plan: "Тандоо",
        popular: "Популярдуу",
        plan_2_subtitle: "Кардар чогултуучу сайт + системаларды туташтыруу",
        p2_f1: "Premium UI/UX Landing Page",
        p2_f2: "Google Sheets интеграциясы",
        p2_f3: "Telegram Бот жана Топко билдирмелер",
        p2_f4: "Instagram API автоматташтыруу туташуусу",
        plan_3_subtitle: "Даяр веб-сайт системасы жана кардарлар агымы чогуу",
        p3_f1: "Толук VIP Автоматташтыруу пакети",
        p3_f2: "Facebook & Instagram Таргет жөндөө",
        p3_f3: "Креативдүү жарнама тексттери жана сунуштар",
        p3_f4: "7 күндүк жарнама мониторинги",
        faq_title: "Көп берилүүчү суроолор",
        faq_desc: "Негизги суроолорго ачык жана так жоопторубуз.",
        faq_q1: "Сайтка келген табыштамаларды кайдан көрөбүз?",
        faq_a1: "Бардык табыштамалар реалдуу убакыт режиминде сиздин Google Drive аккаунтуңуздагы Google Sheets (Таблица) файлына түшөт. Ошондой эле ыңгайлуулук үчүн аларды Telegram тобуңузга бот аркылуу бир секундда багыттап беребиз.",
        faq_q2: "Instagram автоматташтыруу эмне берет?",
        faq_a2: "Кардар Instagram Direct же комментарийлерде белгилүү бир сөздү жазганда (мисалы: 'баасы'), биз орноткон API системасы ага автоматтык түрдө сайттын шилтемесин же атайын сунушту жөнөтөт жана кардарды лоялдуу сатып алуучуга айлантат.",
        faq_q3: "Таргет жарнама үчүн бюджетти ким берет?",
        faq_a3: "Биздин кызматтын баасы жарнаманы туура жана кесипкөй жөндөөнү гана камтыйт. Жарнаманын күнүмдүк же айлык бюджети (Meta компаниясына төлөнүүчү акча) кардар тарабынан өзүнчө берилет.",
        form_title: "Келиңиз, долбооруңузду баштайбыз",
        form_desc: "Форманы толтуруңуз. Биз бизнесиңиз үчүн эң мыкты санариптик чечимди сунуштайбыз.",
        form_label_name: "Атыңыз",
        form_placeholder_name: "Алишер",
        form_label_surname: "Фамилияңыз",
        form_placeholder_surname: "Асимов",
        form_label_phone: "Телефон номериңиз",
        form_placeholder_number: "+998",
        form_label_package: "Сизге кайсы пакет туура келет?",
        form_label_desc: "Долбоор жөнүндө кыскача маалымат (Милдеттүү эмес)",
        form_submit: "Табыштаманы жөнөтүү",
        footer_text: "Бизнести автоматташтыруу боюнча сиздин кесипкөй санариптик өнөктөшүңүз.",
        contacts_text: "Байланыш маалыматы",
        adress_text: "Ош шаары, Айни көчөсү, 114.",
        ish_text: "Иштөө убактысы.",
        kun_text: "Дүйшөмбү - Жума:",
        shanba_text: "Ишемби:",
        dam_text: "Жекшемби: Эс алуу күнү",
        social_text: "Бизге кошулуңуз",
        copy_text: "&copy; 2026 DEV.ALOSHIY.COM — Бардык укуктар корголгон."
    }
};
